### ISSUE TITLE
Evaluate existing routes

### ISSUE THREAD

**Issue by lpww** [nearform/optic#14]
Many of these routes may not be needed anymore since we have switched to browser's storage. I think the only thing we're storing are push notification subscriptions. So, I would expect to see only those and the endpoints to trigger notifications and respond for approval/rejection. We should review this hunch and remove unnecessary routes https://github.com/nearform/optic/tree/master/server/routes

**Comment by simoneb** [comment]
After the fastify refactor this happened implicitly and the routes should now be good and aligned with the functionality of the application
