### ISSUE TITLE
Change confirm action api to never error

### ISSUE THREAD

**Issue by lpww** [nearform/optic#18]
In the `confirm` action, we currently reject the promise if the confirmation is cancelled. This means we need special error handling to prevent confirmation canceling to cause errors in our logs. A better solution would be to always resolve the promise and use a boolean to indicate whether it was confirmed or cancelled. Eg:

```
const { confirmed } = await confirm(options)
if (!confirmed) return
// do confirmed stuff
```

**Comment by radomird** [comment]
This issue is not relevant anymore since we decommissioned the web app.

**Comment by simoneb** [comment]
Are you sure this was on the client rather than the server?

**Comment by radomird** [comment]
@simoneb based on this commit: https://github.com/nearform/optic/commit/9d126c6133ed9435c8616415e189efd76b2ef58e I think the "Confirm" functionality was in the web app.

I've also consulted with @sameer-coder in this matter.
