### ISSUE TITLE
cleanup db properly

### ISSUE THREAD

**Issue by simoneb** [nearform/optic#21]
review data that remains in the db and should no longer be there:

- approved requests
- deleted tokens
- ...

**Comment by simoneb** [comment]
@sameer-coder can you check if this can now be closed? I suspect we are doing some clean up now, not sure if everywhere though

**Comment by sameer-coder** [comment]
@simoneb We are not deleting the requests after they have been approved/declined. I can add that change to my existing PR

**Comment by simoneb** [comment]
Yes please, I thought that had been added already!
