### ISSUE TITLE
Make deployment consistent with other apps

### ISSUE THREAD

**Issue by simoneb** [nearform/optic#218]
Production release should trigger only upon creating a new release, which means we also need to integrate optic (release automation action) in this repo.

Inspire from how it's done e.g. in https://github.com/nearform/optic-release-automation-app

**Comment by Pehesi97** [comment]
@simoneb @zimny if I understood the task well, I guess that's it, right? This doesn't look like an app we publish to npm, so no `npm-token`. Again, I might be wrong. Please correct me if so.

I guess I'm unable to test it until we merge this PR into `master`.
