### ISSUE TITLE
Multiple tokens per secret

### ISSUE THREAD

**Issue by allforabit** [nearform/optic#50]
This issue relates to a new feature being added to optic-expo that allows multiple tokens to be generated for a single token. https://github.com/nearform/optic-expo/issues/196

Currently each secret can have only hold one token due to the way it's modelled in the firebase db (an object with a single key).

**Comment by simoneb** [comment]
When designing this, let's consider also performance implications about looking up data in the db. It's less of an issue on the client where we can reasonably expect that the data is smaller and is stored in memory
