### ISSUE TITLE
Include the token with the push notification to the expo app

### ISSUE THREAD

**Issue by allforabit** [nearform/optic#51]
Currently the mobile app has no way to correlate tokens with locally store notes when a request for a OTA arrives in. The push notification payload should include the token that is currently being used.

**Comment by allforabit** [comment]
I noticed that the token that's being sent is the wrong one and I've included a fix in the attached PR.

**Comment by simoneb** [comment]
@allforabit can you clarify this please? does it mean that the application is not currently working?

**Comment by allforabit** [comment]
No it's still working. The current version sends data with a token field that is the expo token but isn't currently being used in the app. @sameer-coder understandingly assumed that the app was already sending the token and while this is true it's actually the expo subscription token and not the token that is being validated for the OTP request which is the token that I need for the new feature.

**Comment by simoneb** [comment]
Gotcha, thanks. Yes there is indeed some confusion with overlapping terminology here
