### ISSUE TITLE
Redirect to optic-expo

### ISSUE THREAD

**Issue by Eomm** [nearform/optic#62]
The website link is a blank page https://optic-zf3votdk5a-ew.a.run.app/

We should redirect the user to https://expo.dev/@nearform/optic-expo or provide to the dev more info.
The `usage` section https://github.com/nearform/optic#usage seems no more up-to-date aligned with the code base too.

Wdyt @simoneb ?

**Comment by simoneb** [comment]
Yes let's fix it. The link to the app it's because that's where the backend is running, but we can change that too. Originally there was a UI, not anymore.
