### ISSUE TITLE
Turn on test coverage

### ISSUE THREAD

**Issue by simoneb** [nearform/optic#66]
Currently we're not testing for coverage. We should turn it on and use appropriate thresholds to avoid failing the build but also preventing coverage from decreasing. 

Let's also configure this in .taprc instead of CLI flags

**Comment by TomasTM** [comment]
@simoneb what would be an appropriate threshold? 100%? 

This is what we currently have:

<img width="552" alt="Screenshot 2022-01-06 at 15 22 31" src="https://user-images.githubusercontent.com/17081313/148406186-f53b97ae-9069-4e19-bd65-8913c4adb1ba.png">

**Comment by simoneb** [comment]
We should set the thresholds in .taprc file to whatever we have now, so to avoid decreasing in the future. No need to add new tests to get us to 100% now
